#!/usr/bin/env bash
# Generate a project structure index for AI context.
# Output: .autonomy/project_index.md (or custom path via $1)
#
# Usage: index-project.sh [output_path]

set -euo pipefail

OUTPUT_FILE="${1:-.autonomy/project_index.md}"
EXCLUDE_DIRS="node_modules|.git|dist|build|.autonomy|__pycache__|.next|.nuxt|vendor|.venv|venv|coverage"

cat > "$OUTPUT_FILE" <<'HEADER'
# Project Structure Index
<!-- Auto-generated by index-project.sh. Do not edit manually. -->

HEADER

# --- Directory Tree (depth 3) ---
echo "## Directory Tree" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
if command -v find &>/dev/null; then
  find . -maxdepth 3 -type d \
    | grep -vE "/(${EXCLUDE_DIRS})(/|$)" \
    | grep -v '^\.$' \
    | sort \
    | sed 's|^./||' \
    >> "$OUTPUT_FILE" 2>/dev/null || true
fi
echo '```' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- File Type Statistics (top 15) ---
echo "## File Type Statistics" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
find . -type f \
  | grep -vE "/(${EXCLUDE_DIRS})(/|$)" \
  | sed 's/.*\.//' \
  | grep -v '/' \
  | sort \
  | uniq -c \
  | sort -rn \
  | head -15 \
  >> "$OUTPUT_FILE" 2>/dev/null || true
echo '```' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- Tech Stack Detection ---
echo "## Tech Stack" >> "$OUTPUT_FILE"

detect_stack() {
  local file="$1" label="$2"
  if [[ -f "$file" ]]; then
    echo "- **${label}**: \`${file}\`" >> "$OUTPUT_FILE"
  fi
}

detect_stack "package.json" "Node.js / JavaScript"
detect_stack "requirements.txt" "Python (pip)"
detect_stack "pyproject.toml" "Python (modern)"
detect_stack "Pipfile" "Python (pipenv)"
detect_stack "go.mod" "Go"
detect_stack "Cargo.toml" "Rust"
detect_stack "pom.xml" "Java (Maven)"
detect_stack "build.gradle" "Java/Kotlin (Gradle)"
detect_stack "Gemfile" "Ruby"
detect_stack "composer.json" "PHP"
detect_stack "Makefile" "Make"
detect_stack "CMakeLists.txt" "C/C++ (CMake)"
detect_stack "Dockerfile" "Docker"
detect_stack "docker-compose.yml" "Docker Compose"
detect_stack "docker-compose.yaml" "Docker Compose"
detect_stack "tsconfig.json" "TypeScript"
detect_stack ".eslintrc.json" "ESLint"
detect_stack ".eslintrc.js" "ESLint"
detect_stack "tailwind.config.js" "Tailwind CSS"
detect_stack "tailwind.config.ts" "Tailwind CSS"
detect_stack "next.config.js" "Next.js"
detect_stack "next.config.mjs" "Next.js"
detect_stack "nuxt.config.ts" "Nuxt"
detect_stack "vite.config.ts" "Vite"
detect_stack "vite.config.js" "Vite"

echo "" >> "$OUTPUT_FILE"

# --- Key Entry Points ---
echo "## Key Entry Points" >> "$OUTPUT_FILE"

detect_entry() {
  local file="$1" label="$2"
  if [[ -f "$file" ]]; then
    echo "- \`${file}\` — ${label}" >> "$OUTPUT_FILE"
  fi
}

detect_entry "src/index.ts" "Main entry (TypeScript)"
detect_entry "src/index.js" "Main entry (JavaScript)"
detect_entry "src/main.ts" "Main entry (TypeScript)"
detect_entry "src/main.js" "Main entry (JavaScript)"
detect_entry "src/app.ts" "App entry (TypeScript)"
detect_entry "src/app.js" "App entry (JavaScript)"
detect_entry "app.py" "App entry (Python)"
detect_entry "main.py" "Main entry (Python)"
detect_entry "manage.py" "Django management"
detect_entry "main.go" "Main entry (Go)"
detect_entry "cmd/main.go" "Main entry (Go)"
detect_entry "src/main.rs" "Main entry (Rust)"
detect_entry "index.html" "HTML entry"
detect_entry "src/App.tsx" "React App component"
detect_entry "src/App.jsx" "React App component"
detect_entry "pages/index.tsx" "Next.js index page"
detect_entry "pages/index.js" "Next.js index page"
detect_entry "app/page.tsx" "Next.js App Router page"
detect_entry "app/layout.tsx" "Next.js App Router layout"

echo "" >> "$OUTPUT_FILE"

# --- Timestamp ---
echo "---" >> "$OUTPUT_FILE"
echo "_Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)_" >> "$OUTPUT_FILE"
